<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>shadowguard-cli</AssemblyName>
    <RootNamespace>ShadowGuard.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ShadowGuard.Core\ShadowGuard.Core.csproj" />
  </ItemGroup>
</Project>
